{% set name = "diffpy.pdffit2" %}
{% set version = "1.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/diffpy/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 093980832ebed9bd54f1b4d61d72ce43136a42653f98e76b99d9bcaf6677a682

build:
  # we need egg_dir to avoid overlapping diffpy/__init__.py files.
  preserve_egg_dir: true
  number: 6
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}     # [py3k or not win]
    - gsl {{ gsl }}
  host:
    - python
    - pip
    - setuptools
    - gsl {{ gsl }}
  run:
    - python
    - setuptools
    - six
    - diffpy.structure
    - gsl {{ gsl }}

test:
  imports:
    - diffpy
    - diffpy.pdffit2
    - diffpy.pdffit2.pdffit2
    - diffpy.pdffit2.ipy_ext
    - diffpy.pdffit2.tests
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/diffpy/diffpy.pdffit2
  summary: PDFfit2 - real space structure refinement program.
  description: |
    The diffpy.pdffit2 package provides functions for calculation and refinement of atomic pair distribution function 
    from crystal structure model. It is used as a computational engine by PDFgui, which provides a simple, fast, and 
    easy-to-use user interface for chemists, physicists, and materials scientists.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://www.diffpy.org/doc/pdffit2
  dev_url: https://github.com/diffpy/diffpy.pdffit2

extra:
  recipe-maintainers:
    - dragonyanglong
    - sbillinge
